### ISSUE TITLE
Amendment - Trips/Hackathon Secretary

### ISSUE THREAD

**Issue by evadavis** [HackSocNotts/nominations#6]
# Trips and Hackathon Secretary

# Description
Considering we as a society have a fair amount of trips (such as the trip to the National Museum of Computing, Nottingham Hackspace, etc) as well as group trips to numerous hackathons during the year, I think it would be a good idea to have another role added into committee. This person would have sole responsibility of organising potential trips to hackathons and other areas of interest. This would include keeping up-to-date on upcoming hackathons and making sure that members of HackSoc are aware of them so they can participate if they want to.
However, it may be a bit much to have 8 people on the committee so if this isn't popular, I propose to add it as an additional job to be overseen by another committee member (such as Dev Sec or Gen Sec). This is because it is currently not in the constitution at all for any committee member to be responsible for it and I feel that as it is an important part of HackSoc, that should not be the case.

**Comment by dthelegend** [comment]
I second this proposal. Going to hackathons is important, and HackSoc is a large Society: it's a miracle it runs with only 7 committee members and as such an expansion like this sounds like it would help reduce the workload on Gen Sec (maybe I'm biased) and streamline the role.

**Comment by zac-garby** [comment]
Agreed. I guess this wasn't a thing for the past few years due to COVID not letting us travel to events, but now we can (and now we have the money for it) this would be great to focus more on!
